

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

jobs:
  - job: build
    steps:
    - powershell: ./.tools/discord/sendwebhook.ps1 start $(WEBHOOK_URL)
      displayName: 'Notify start'
    - script: .paket\paket.exe restore --group Build
      displayName: 'Restore packages'
    - script: build.bat
      displayName: 'Run build'
    - task: PublishBuildArtifacts@1
      displayName: 'Package artifacts'
      inputs:
        PathtoPublish: 'BenchmarkDotNet.Artifacts\results'
        ArtifactName: 'EsiStatics.Benchmarks.Results'
        publishLocation: 'Container'
    - powershell: ./.tools/discord/sendwebhook.ps1 success $(WEBHOOK_URL)
      displayName: 'Notify success'

  - job: failure
    dependsOn: build
    condition: failed()
    steps:
    - powershell: ./.tools/discord/sendwebhook.ps1 failure $(WEBHOOK_URL)
      displayName: 'Notify failure'
